# 
#   Muna
#   Copyright © 2026 NatML Inc. All Rights Reserved.
#

from __future__ import annotations
from PIL import Image
from pydantic import BaseModel, ConfigDict, Field
from requests import Response
from typing import Literal, TypedDict

ChatCompletionReasoningEffort = Literal["minimal", "low", "medium", "high", "xhigh"]
SpeechResponseFormat = Literal["mp3", "opus", "aac", "flac", "wav", "pcm"]
SpeechStreamFormat = Literal["audio", "sse"]

class ChatCompletion(BaseModel):
    class Usage(BaseModel):
        class PromptTokensDetails(BaseModel):
            audio_tokens: int | None = Field(None, description="Audio input tokens present in the prompt.")
            cache_write_tokens: int | None = Field(None, description="The unadjusted number of prompt tokens written to cache.")
            cached_tokens: int | None = Field(None, description="Cached tokens present in the prompt.")
        class CompletionTokensDetails(BaseModel):
            reasoning_tokens: int | None = Field(None, description="Tokens generated by the model for reasoning.")
        prompt_tokens: int = Field(description="Number of tokens in the prompt.")
        completion_tokens: int = Field(description="Number of tokens in the generated completion.")
        total_tokens: int = Field(description="Total number of tokens used in the request.")
        prompt_tokens_details: PromptTokensDetails | None = Field(None, description="Breakdown of tokens used in the prompt.")
        completion_tokens_details: CompletionTokensDetails | None = Field(None, description="Breakdown of tokens used in the completion.")
    object: Literal["chat.completion"] = Field("chat.completion", init=False)
    id: str = Field(description="Chat completion unique identifier.")
    created: int = Field(description="Creation date unix timestamp in seconds.")
    model: str = Field(description="Model that created chat completion.")
    choices: list[Choice]
    usage: Usage = Field(description="Usage statistics in the completion.")

class ChatCompletionChunk(BaseModel):
    object: Literal["chat.completion.chunk"] = Field("chat.completion.chunk", init=False)
    id: str
    created: int
    model: str
    choices: list[StreamChoice]
    usage: ChatCompletion.Usage | None = None

class Choice(BaseModel):
    index: int
    message: Message
    finish_reason: Literal["stop", "length", "content_filter", "tool_calls"] | None = None

class StreamChoice(BaseModel):
    index: int
    delta: DeltaMessage | None
    finish_reason: Literal["stop", "length", "content_filter", "tool_calls"] | None = None

class Message(BaseModel):
    role: Literal["assistant", "user", "system"]
    content: str | None = None
    reasoning_content: str | None = Field(None, description="Reasoning contents of the message, before the final answer. Follows the DeepSeek convention for reasoning models.")

class DeltaMessage(BaseModel):
    role: Literal["assistant", "user", "system"] | None = None
    content: str | None = None
    reasoning_content: str | None = Field(None, description="Reasoning contents of the message delta, before the final answer. Follows the DeepSeek convention for reasoning models.")

class Embedding(BaseModel):
    object: Literal["embedding"]
    embedding: list[float] | str
    index: int

class EmbeddingCreateResponse(BaseModel):
    class Usage(BaseModel):
        prompt_tokens: int
        total_tokens: int
    object: Literal["list"]
    model: str
    data: list[Embedding]
    usage: Usage

class SpeechCreateResponse(BaseModel, **ConfigDict(arbitrary_types_allowed=True)):
    content: bytes
    response: Response

class Transcription(BaseModel):
    class TokenUsage(BaseModel):
        class InputTokenDetails(BaseModel):
            audio_tokens: int
            text_tokens: int
        type: Literal["tokens"]
        input_tokens: int
        output_tokens: int
        total_tokens: int
        input_token_details: InputTokenDetails
    class DurationUsage(BaseModel):
        type: Literal["duration"]
        seconds: float
    text: str
    usage: TokenUsage | DurationUsage

class ImageData(BaseModel, **ConfigDict(arbitrary_types_allowed=True)):
    b64_json: str | None
    image: Image.Image | None

class ImageResponse(BaseModel):
    class Usage(BaseModel):
        class UsageInputTokensDetails(BaseModel):
            image_tokens: int = Field(description="The number of image tokens in the input prompt.")
            text_tokens: int = Field(description="The number of text tokens in the input prompt.")
        class UsageOutputTokensDetails(BaseModel):
            image_tokens: int = Field(description="The number of image output tokens generated by the model.")
            text_tokens: int = Field(description="The number of text output tokens generated by the model.")
        input_tokens: int = Field(description="The number of tokens (images and text) in the input prompt.")
        output_tokens: int = Field(description="The number of output tokens generated by the model.")
        total_tokens: int = Field(description="The total number of tokens (images and text) used for the image generation.")
        input_tokens_details: UsageInputTokensDetails = Field(description="The input tokens detailed information for the image generation.")
        output_tokens_details: UsageOutputTokensDetails | None = Field(default=None, description="The output token details for the image generation.")
    data: list[ImageData] | None = Field(description="The list of generated images.")
    background: Literal["transparent", "opaque"] | None = Field(description="The background parameter used for the image generation.")
    created: int = Field(description="The Unix timestamp (in seconds) of when the image was created.")
    usage: Usage | None = Field(default=None, description="the token usage information for the image generation.")

class _MessageDict(TypedDict): # For text completion
    role: Literal["assistant", "user", "system"]
    content: str | None

class _ResponseFormatTextDict(TypedDict):
    type: Literal["text"]

class _ResponseFormatJsonSchemaDict(TypedDict):
    type: Literal["json_schema"]
    json_schema: dict[str, object]

_ResponseFormatDict = _ResponseFormatTextDict | _ResponseFormatJsonSchemaDict