# 
#   Muna
#   Copyright © 2026 NatML Inc. All Rights Reserved.
#

from __future__ import annotations
from PIL import Image
from pydantic import BaseModel, ConfigDict, Field, JsonValue
from requests import Response
from typing import Annotated, Literal, NotRequired, TypedDict

ChatCompletionReasoningEffort = Literal["minimal", "low", "medium", "high", "xhigh"]
SpeechResponseFormat = Literal["mp3", "opus", "aac", "flac", "wav", "pcm"]
SpeechStreamFormat = Literal["audio", "sse"]

class ChatCompletion(BaseModel):
    class Message(BaseModel):
        """
        Message returned in a chat completion choice.
        """
        role: Literal["assistant", "user", "system", "tool"]
        content: str | None = None
        reasoning_content: str | None = Field(None, description="Reasoning contents of the message, before the final answer. Follows the DeepSeek convention for reasoning models.")
        tool_calls: list[ChatCompletionMessageFunctionToolCall] | None = Field(None, description="Tool calls generated by the model.")
    class Usage(BaseModel):
        class PromptTokensDetails(BaseModel):
            audio_tokens: int | None = Field(None, description="Audio input tokens present in the prompt.")
            cache_write_tokens: int | None = Field(None, description="The unadjusted number of prompt tokens written to cache.")
            cached_tokens: int | None = Field(None, description="Cached tokens present in the prompt.")
        class CompletionTokensDetails(BaseModel):
            reasoning_tokens: int | None = Field(None, description="Tokens generated by the model for reasoning.")
        prompt_tokens: int = Field(description="Number of tokens in the prompt.")
        completion_tokens: int = Field(description="Number of tokens in the generated completion.")
        total_tokens: int = Field(description="Total number of tokens used in the request.")
        prompt_tokens_details: PromptTokensDetails | None = Field(None, description="Breakdown of tokens used in the prompt.")
        completion_tokens_details: CompletionTokensDetails | None = Field(None, description="Breakdown of tokens used in the completion.")
    object: Literal["chat.completion"] = Field("chat.completion", init=False)
    id: str = Field(description="Chat completion unique identifier.")
    created: int = Field(description="Creation date unix timestamp in seconds.")
    model: str = Field(description="Model that created chat completion.")
    choices: list[Choice]
    usage: Usage = Field(description="Usage statistics in the completion.")

class ChatCompletionChunk(BaseModel):
    object: Literal["chat.completion.chunk"] = Field("chat.completion.chunk", init=False)
    id: str
    created: int
    model: str
    choices: list[StreamChoice]
    usage: ChatCompletion.Usage | None = None

class Choice(BaseModel):
    index: int
    message: ChatCompletion.Message
    finish_reason: Literal["stop", "length", "content_filter", "tool_calls"] | None = None

class StreamChoice(BaseModel):
    index: int
    delta: DeltaMessage | None
    finish_reason: Literal["stop", "length", "content_filter", "tool_calls"] | None = None

class ChatCompletionContentPartText(BaseModel):
    type: Literal["text"] = Field("text", init=False)
    text: str = Field(description="The text content.")

class ChatCompletionContentPartImage(BaseModel):
    class ImageURL(BaseModel):
        url: str = Field(description="Either a URL of the image or the base64 encoded image data.")
        detail: Literal["auto", "low", "high"] | None = Field(None, description="Specifies the detail level of the image.")
    type: Literal["image_url"] = Field("image_url", init=False)
    image_url: ImageURL

class ChatCompletionContentPartInputAudio(BaseModel):
    class InputAudio(BaseModel):
        data: str = Field(description="Base64 encoded audio data.")
        format: Literal["wav", "mp3"] = Field(description="The format of the encoded audio data.")
    type: Literal["input_audio"] = Field("input_audio", init=False)
    input_audio: InputAudio

class ChatCompletionContentPartFile(BaseModel):
    class File(BaseModel):
        file_data: str | None = Field(None, description="The base64 encoded file data.")
        file_id: str | None = Field(None, description="The ID of an uploaded file to use as input.")
        filename: str | None = Field(None, description="The name of the file.")
    type: Literal["file"] = Field("file", init=False)
    file: File

class ChatCompletionContentPartRefusal(BaseModel):
    # Assistant-side; appears when clients replay history containing refusals.
    type: Literal["refusal"] = Field("refusal", init=False)
    refusal: str = Field(description="The refusal message generated by the model.")

ChatCompletionContentPart = Annotated[
    ChatCompletionContentPartText       |
    ChatCompletionContentPartImage      |
    ChatCompletionContentPartInputAudio |
    ChatCompletionContentPartFile       |
    ChatCompletionContentPartRefusal,
    Field(discriminator="type")
]

class FunctionDefinition(BaseModel):
    name: str = Field(description="The name of the function to be called.")
    description: str | None = Field(None, description="A description of what the function does, used by the model to choose when and how to call the function.")
    parameters: dict[str, JsonValue] | None = Field(None, description="The parameters the function accepts, described as a JSON Schema object.")
    strict: bool | None = Field(None, description="Whether to enable strict schema adherence when generating the function call.")

class ChatCompletionFunctionTool(BaseModel):
    type: Literal["function"] = Field("function", init=False)
    function: FunctionDefinition

class ChatCompletionMessageFunctionToolCall(BaseModel):
    class Function(BaseModel):
        name: str = Field(description="The name of the function to call.")
        arguments: str = Field(description="The arguments to call the function with, as a JSON-encoded string.")
    id: str = Field(description="The ID of the tool call.")
    type: Literal["function"] = Field("function", init=False)
    function: Function

class ChoiceDeltaToolCall(BaseModel):
    class Function(BaseModel):
        name: str | None = None
        arguments: str | None = None
    index: int
    id: str | None = None
    type: Literal["function"] | None = None
    function: Function | None = None

ChatCompletionToolChoice = Literal["auto", "none"]

class Message(TypedDict):
    """
    Chat message.

    A plain dict so compiled chat predictors pass the conversation straight to the
    tokenizer's chat template, which normalizes content parts itself. Optional fields
    are omitted when absent.
    """
    role: Literal["assistant", "user", "system", "tool"]
    content: str | list[ChatCompletionContentPart] | None
    reasoning_content: NotRequired[str | None]
    tool_calls: NotRequired[list[ChatCompletionMessageFunctionToolCall] | None]
    tool_call_id: NotRequired[str | None]

class DeltaMessage(BaseModel):
    role: Literal["assistant", "user", "system", "tool"] | None = None
    content: str | None = None
    reasoning_content: str | None = Field(None, description="Reasoning contents of the message delta, before the final answer. Follows the DeepSeek convention for reasoning models.")
    tool_calls: list[ChoiceDeltaToolCall] | None = Field(None, description="Streamed tool call fragments, accumulated by `index`.")

class Embedding(BaseModel):
    object: Literal["embedding"]
    embedding: list[float] | str
    index: int

class EmbeddingCreateResponse(BaseModel):
    class Usage(BaseModel):
        prompt_tokens: int
        total_tokens: int
    object: Literal["list"]
    model: str
    data: list[Embedding]
    usage: Usage

class SpeechCreateResponse(BaseModel, **ConfigDict(arbitrary_types_allowed=True)):
    content: bytes
    response: Response

class Transcription(BaseModel):
    class TokenUsage(BaseModel):
        class InputTokenDetails(BaseModel):
            audio_tokens: int
            text_tokens: int
        type: Literal["tokens"]
        input_tokens: int
        output_tokens: int
        total_tokens: int
        input_token_details: InputTokenDetails
    class DurationUsage(BaseModel):
        type: Literal["duration"]
        seconds: float
    text: str
    usage: TokenUsage | DurationUsage

class ImageData(BaseModel, **ConfigDict(arbitrary_types_allowed=True)):
    b64_json: str | None
    image: Image.Image | None

class ImageResponse(BaseModel):
    class Usage(BaseModel):
        class UsageInputTokensDetails(BaseModel):
            image_tokens: int = Field(description="The number of image tokens in the input prompt.")
            text_tokens: int = Field(description="The number of text tokens in the input prompt.")
        class UsageOutputTokensDetails(BaseModel):
            image_tokens: int = Field(description="The number of image output tokens generated by the model.")
            text_tokens: int = Field(description="The number of text output tokens generated by the model.")
        input_tokens: int = Field(description="The number of tokens (images and text) in the input prompt.")
        output_tokens: int = Field(description="The number of output tokens generated by the model.")
        total_tokens: int = Field(description="The total number of tokens (images and text) used for the image generation.")
        input_tokens_details: UsageInputTokensDetails = Field(description="The input tokens detailed information for the image generation.")
        output_tokens_details: UsageOutputTokensDetails | None = Field(default=None, description="The output token details for the image generation.")
    data: list[ImageData] | None = Field(description="The list of generated images.")
    background: Literal["transparent", "opaque"] | None = Field(description="The background parameter used for the image generation.")
    created: int = Field(description="The Unix timestamp (in seconds) of when the image was created.")
    usage: Usage | None = Field(default=None, description="the token usage information for the image generation.")

class _ResponseFormatTextDict(TypedDict):
    type: Literal["text"]

class _ResponseFormatJsonSchemaDict(TypedDict):
    type: Literal["json_schema"]
    json_schema: dict[str, object]

_ResponseFormatDict = _ResponseFormatTextDict | _ResponseFormatJsonSchemaDict