# 
#   Muna
#   Copyright © 2026 NatML Inc. All Rights Reserved.
#

from __future__ import annotations
from pydantic import BaseModel, Field
from typing import Annotated, Literal

StopReason = Literal[
    "end_turn",
    "max_tokens",
    "stop_sequence",
    "tool_use",
    "pause_turn",
    "refusal"
]

class TextBlock(BaseModel):
    type: Literal["text"]
    text: str = Field(description="Response text.")

ContentBlock = Annotated[
    TextBlock,
    Field(discriminator="type")
]

class Message(BaseModel):
    """
    Message.
    """
    id: str = Field(description="Unique object identifier.")
    type: Literal["message"] = Field(default="message", init=False)
    role: Literal["assistant"] = Field(default="assistant", init=False)
    content: list[ContentBlock] = Field(description="Content generated by the model.")
    model: str = Field(description="The model that will complete your prompt.")
    stop_reason: StopReason | None = Field(description="Reason that we stopped.")
    stop_sequence: str | None = Field(default=None, description="Which custom stop sequence was generated, if any.")
    usage: Usage = Field(description="Billing and rate-limit usage.")

class Usage(BaseModel):
    """
    Billing usage.
    """
    input_tokens: int = Field(description="Number of input tokens which were used.")
    output_tokens: int = Field(description="Number of output tokens which were used.")